import { withBasePath } from "./base-path";

export const page = (n: number) =>
  withBasePath(`/profile-pages/page-${String(n).padStart(2, "0")}.jpg`);

export const PAGES = {
  cover: page(1),
  welcome: page(2),
  aboutOpener: page(3),
  about: page(4),
  philosophyOpener: page(5),
  philosophy: page(6),
  servicesOpener: page(7),
  services: page(8),
  eventsOpener: page(9),
  eventsStage: page(10),
  eventsAlt: page(11),
  boothOpener: page(12),
  boothA: page(13),
  boothB: page(14),
  identityOpener: page(15),
  logoWall: page(16),
  profileA: page(17),
  profileB: page(18),
  menu: page(19),
  cards: page(20),
  applyA: page(21),
  applyB: page(22),
  applyC: page(23),
  applyD: page(24),
  packA: page(25),
  packB: page(26),
  socialOpener: page(27),
  socialA: page(28),
  socialB: page(29),
  socialC: page(30),
  motionOpener: page(31),
  photoA: page(32),
  photoB: page(33),
  adsOpener: page(34),
  adsA: page(35),
  adsB: page(36),
  adsC: page(37),
  giftsOpener: page(38),
  gifts: page(39),
  outdoorOpener: page(40),
  outdoor: page(41),
  webOpener: page(42),
  webA: page(43),
  webB: page(44),
  financeOpener: page(45),
  financeCopy: page(46),
  financeA: page(47),
  financeB: page(48),
  contact: page(49),
  thankYou: page(50),
} as const;
